export interface Employe {
    
    "id": number,
    "firstName": string,
    "lastName": string,
    "dob": number,
    "email": string,
    // "phone": string,
    // "address": string,
    // "city": string,
    // "zip": string,
    // "country": string,
    // "salary": number,
    // "currency": string,
    // "hireDate": number,
    // "resignDate": number,
    // "trialPeriod": number,
    // "resignPeriod": number,
    // "endTrialDate": number,
    // "effectiveResignDate": number,
    // "status": string,
    // "employeeHistoryId": number,
    // "note": string,
    // "employeeId": number,
    // "category": number,
    // "schedulerId": number,
    // "schedulerEnabled": true,
    // "startDate": number,
    // "endDate": number,
    // "repeatEvery": number
  }