export interface Employe {
    
    "id": 0,
    "firstName": "string",
    "lastName": "string",
    "dob": "2022-03-10",
    "email": "string",
    "phone": "string",
    "address": "string",
    "city": "string",
    "zip": "string",
    "country": "string",
    "salary": 0,
    "currency": "string",
    "hireDate": "2022-03-10",
    "resignDate": "2022-03-10",
    "trialPeriod": 0,
    "resignPeriod": 0,
    "endTrialDate": "2022-03-10",
    "effectiveResignDate": "2022-03-10",
    "status": "string",
    "employeeHistoryId": 0,
    "note": "string",
    "employeeId": 0,
    "category": "NOTE",
    "schedulerId": 0,
    "schedulerEnabled": true,
    "startDate": "2022-03-10",
    "endDate": "2022-03-10",
    "repeatEvery": 0
  }